import {
  insertCourseSchema,
  insertLessonSchema,
  insertQuizSchema,
  insertQuestionSchema,
  Course,
  Lesson,
  Quiz,
  Question,
} from '../shared/schema'; // Adjust path if needed based on your final structure

// --- Seed Data for Courses ---
// Note: IDs and createdAt will be generated by the database
export const seedCourses: Omit<Course, 'id' | 'createdAt'>[] = [
  {
    title: 'NGX 101: Introduction to the Nigerian Stock Market',
    description: 'Understand the fundamentals of the Nigerian Exchange Limited (NGX), its key players, and how stocks are traded.',
    imageUrl: '/assets/images/courses/ngx_basics.jpg', // Placeholder image path
    type: 'text',
    level: 'beginner',
  },
  {
    title: 'Reading the Market: Introduction to Technical Analysis',
    description: 'Learn to interpret stock charts, identify trends, and use basic technical indicators for NGX stocks.',
    imageUrl: '/assets/images/courses/technical_analysis_intro.jpg',
    type: 'video',
    level: 'beginner',
  },
  {
    title: 'Investment Strategies for the Nigerian Market',
    description: 'Explore different investment approaches like value investing, growth investing, and dividend investing tailored for the NGX.',
    imageUrl: '/assets/images/courses/investment_strategies.jpg',
    type: 'text',
    level: 'intermediate',
  },
  {
    title: 'Understanding Financial Statements for Investors',
    description: 'Learn how to read and analyze company balance sheets, income statements, and cash flow statements to make informed investment decisions.',
    imageUrl: '/assets/images/courses/financial_statements.jpg',
    type: 'text',
    level: 'intermediate',
  },
  {
    title: 'Advanced Technical Analysis: Patterns & Indicators',
    description: 'Dive deeper into chart patterns (e.g., Head & Shoulders, Triangles) and advanced indicators (e.g., MACD, RSI, Bollinger Bands).',
    imageUrl: '/assets/images/courses/advanced_technical.jpg',
    type: 'video',
    level: 'advanced',
  },
  {
    title: 'Risk Management in Stock Trading',
    description: 'Master techniques to manage risk, set stop-losses, and protect your capital while trading on the NGX.',
    imageUrl: '/assets/images/courses/risk_management.jpg',
    type: 'text',
    level: 'intermediate',
  },
  {
    title: 'Sector Analysis: Opportunities in the Nigerian Economy',
    description: 'Analyze key sectors of the Nigerian economy (e.g., Banking, Consumer Goods, Oil & Gas) and identify potential investment opportunities on the NGX.',
    imageUrl: '/assets/images/courses/sector_analysis.jpg',
    type: 'text',
    level: 'advanced',
  },
  {
    title: 'Building a Diversified Portfolio on the NGX',
    description: 'Learn the principles of diversification and how to construct a balanced portfolio of Nigerian stocks and other assets.',
    imageUrl: '/assets/images/courses/portfolio_building.jpg',
    type: 'video',
    level: 'intermediate',
  },
  {
    title: 'Behavioral Finance: The Psychology of Trading',
    description: 'Understand common psychological biases that affect investment decisions and learn how to overcome them.',
    imageUrl: '/assets/images/courses/behavioral_finance.jpg',
    type: 'text',
    level: 'advanced',
  },
  {
    title: 'Trading Platforms and Order Types on the NGX',
    description: 'Get familiar with popular trading platforms used in Nigeria and understand different order types (market, limit, stop orders).',
    imageUrl: '/assets/images/courses/trading_platforms.jpg',
    type: 'video',
    level: 'beginner',
  },
];

// --- Seed Data for Lessons ---
// Note: courseId uses placeholder IDs (1-10) assuming courses are inserted sequentially.
// Actual seeding script should map these to the real IDs.
export const seedLessons: Omit<Lesson, 'id'>[] = [
  { courseId: 1, title: 'What is the NGX?', content: 'History, function, and importance of the Nigerian Exchange Limited.', videoUrl: null, order: 1 },
  { courseId: 1, title: 'Market Participants', content: 'Roles of stockbrokers, regulators (SEC), CSCS, etc.', videoUrl: null, order: 2 },
  { courseId: 2, title: 'Introduction to Candlestick Charts', content: 'Understanding Open, High, Low, Close (OHLC) and basic patterns.', videoUrl: '/assets/videos/lessons/candlesticks_intro.mp4', order: 1 },
  { courseId: 2, title: 'Support and Resistance Levels', content: 'Identifying key price levels on charts.', videoUrl: '/assets/videos/lessons/support_resistance.mp4', order: 2 },
  { courseId: 3, title: 'Value Investing Principles', content: 'Finding undervalued stocks based on fundamentals.', videoUrl: null, order: 1 },
  { courseId: 4, title: 'Decoding the Income Statement', content: 'Understanding revenue, costs, and profitability.', videoUrl: null, order: 1 },
  { courseId: 5, title: 'Moving Averages (SMA & EMA)', content: 'Using moving averages to identify trends.', videoUrl: '/assets/videos/lessons/moving_averages.mp4', order: 1 },
  { courseId: 6, title: 'Position Sizing Strategies', content: 'Determining how much capital to allocate per trade.', videoUrl: null, order: 1 },
  { courseId: 7, title: 'Analyzing the Nigerian Banking Sector', content: 'Key metrics and factors affecting bank stocks.', videoUrl: null, order: 1 },
  { courseId: 10, title: 'Placing a Market Order', content: 'How to execute a market order on a typical platform.', videoUrl: '/assets/videos/lessons/market_order.mp4', order: 1 },
];

// --- Seed Data for Quizzes ---
// Note: courseId uses placeholder IDs (1-10).
export const seedQuizzes: Omit<Quiz, 'id'>[] = [
  { courseId: 1, title: 'NGX Basics Quiz', description: 'Test your understanding of the Nigerian stock market fundamentals.' },
  { courseId: 2, title: 'Chart Reading Essentials', description: 'Quiz on basic technical analysis concepts.' },
  { courseId: 3, title: 'Investment Strategy Check', description: 'Assess your knowledge of different investment approaches.' },
  { courseId: 4, title: 'Financial Statement Literacy', description: 'Test your ability to interpret key financial reports.' },
  { courseId: 5, title: 'Technical Indicators Quiz', description: 'Check your understanding of common technical indicators.' },
  { courseId: 6, title: 'Risk Management Principles', description: 'Quiz on managing trading risk.' },
  { courseId: 7, title: 'Nigerian Sector Knowledge', description: 'Test your awareness of key NGX sectors.' },
  { courseId: 8, title: 'Portfolio Diversification Quiz', description: 'Assess your understanding of building a balanced portfolio.' },
  { courseId: 9, title: 'Behavioral Biases Check', description: 'Identify common psychological pitfalls in trading.' },
  { courseId: 10, title: 'Trading Execution Quiz', description: 'Test your knowledge of order types and platforms.' },
];

// --- Seed Data for Questions ---
// Note: quizId uses placeholder IDs (1-10).
// options array index starts at 0, correctOption refers to the index of the correct answer.
export const seedQuestions: Omit<Question, 'id'>[] = [
  { quizId: 1, questionText: 'What is the primary regulator of the Nigerian capital markets?', options: ['CBN', 'NGX', 'SEC', 'CSCS'], correctOption: 2, explanation: 'The Securities and Exchange Commission (SEC) is the apex regulator.', order: 1 },
  { quizId: 1, questionText: 'What does CSCS stand for?', options: ['Central Securities Clearing System', 'Central Stock Control System', 'Capital Share Clearing Service', 'Company Security Certification Service'], correctOption: 0, explanation: 'CSCS is the Central Securities Clearing System, responsible for clearing and settlement.', order: 2 },
  { quizId: 2, questionText: 'A candlestick with a long upper shadow and small real body typically indicates:', options: ['Strong buying pressure', 'Strong selling pressure near the high', 'Indecision', 'A market bottom'], correctOption: 1, explanation: 'A long upper shadow shows that buyers pushed prices up, but sellers pushed them back down, indicating selling pressure.', order: 1 },
  { quizId: 3, questionText: 'Which strategy focuses on buying stocks perceived to be trading below their intrinsic value?', options: ['Growth Investing', 'Dividend Investing', 'Value Investing', 'Momentum Trading'], correctOption: 2, explanation: 'Value investing involves identifying and buying undervalued securities.', order: 1 },
  { quizId: 4, questionText: 'Which statement shows a company\'s assets, liabilities, and equity at a specific point in time?', options: ['Income Statement', 'Cash Flow Statement', 'Balance Sheet', 'Annual Report'], correctOption: 2, explanation: 'The Balance Sheet provides a snapshot of a company\'s financial position.', order: 1 },
  { quizId: 5, questionText: 'What does RSI (Relative Strength Index) primarily measure?', options: ['Trend direction', 'Market volatility', 'Overbought/Oversold conditions', 'Trading volume'], correctOption: 2, explanation: 'RSI is a momentum oscillator used to identify overbought or oversold conditions.', order: 1 },
  { quizId: 6, questionText: 'A stop-loss order is designed to:', options: ['Guarantee a profit', 'Limit potential losses on a trade', 'Buy more shares automatically', 'Execute only at the end of the day'], correctOption: 1, explanation: 'A stop-loss order automatically sells a security when it reaches a certain price to limit losses.', order: 1 },
  { quizId: 7, questionText: 'Which of these is a major component of the NGX All-Share Index?', options: ['Technology Stocks', 'Banking Stocks', 'Agricultural Stocks', 'Mining Stocks'], correctOption: 1, explanation: 'Banking stocks traditionally have a significant weighting in the NGX ASI.', order: 1 },
  { quizId: 9, questionText: 'Buying a stock simply because its price has been rising rapidly is an example of:', options: ['Anchoring Bias', 'Herd Mentality', 'Confirmation Bias', 'Loss Aversion'], correctOption: 1, explanation: 'Herd mentality involves following the crowd, often seen in momentum chasing.', order: 1 },
  { quizId: 10, questionText: 'Which order type guarantees execution but not the price?', options: ['Limit Order', 'Stop Order', 'Market Order', 'Stop-Limit Order'], correctOption: 2, explanation: 'A market order is executed immediately at the best available current price.', order: 1 },
];


// --- Seeding Function (Conceptual - Updated) ---
// This function would need to be implemented in a separate script
// that connects to your database using Drizzle ORM.
import { db } from './storage'; // Your configured Drizzle instance
import { courses, lessons, quizzes, questions } from '../shared/schema'; // Import table schemas

export async function seedDatabase() {
  console.log('Seeding database (Courses, Lessons, Quizzes, Questions)...');

  // Optional: Clear existing data first (use with caution!)
  // await db.delete(questions);
  // await db.delete(quizzes);
  // await db.delete(lessons);
  // await db.delete(courses);

  // Seed Courses
  const insertedCourses = await db.insert(courses).values(seedCourses).returning({ id: courses.id });
  console.log(`Inserted ${insertedCourses.length} courses.`);

  // Helper to map placeholder Course IDs (1-10) to actual inserted IDs
  const courseIdMap = insertedCourses.reduce((acc: Record<number, number>, course: { id: number }, index: number) => {
    acc[index + 1] = course.id; // Assumes seedCourses[index] corresponds to insertedCourses[index]
    return acc;
  }, {} as Record<number, number>);

  // Seed Lessons
  const lessonInsertData = seedLessons.map(l => ({
    ...l,
    courseId: courseIdMap[l.courseId] // Map placeholder ID to actual ID
  }));
  const insertedLessons = await db.insert(lessons).values(lessonInsertData).returning({ id: lessons.id });
  console.log(`Inserted ${insertedLessons.length} lessons.`);

  // Seed Quizzes
  const quizInsertData = seedQuizzes.map(q => ({
    ...q,
    courseId: courseIdMap[q.courseId] // Map placeholder ID to actual ID
  }));
  const insertedQuizzes = await db.insert(quizzes).values(quizInsertData).returning({ id: quizzes.id });
  console.log(`Inserted ${insertedQuizzes.length} quizzes.`);

  // Helper to map placeholder Quiz IDs (1-10) to actual inserted IDs
   const quizIdMap = insertedQuizzes.reduce((acc: Record<number, number>, quiz: { id: number }, index: number) => {
    acc[index + 1] = quiz.id; // Assumes seedQuizzes[index] corresponds to insertedQuizzes[index]
    return acc;
  }, {} as Record<number, number>);

  // Seed Questions
  const questionInsertData = seedQuestions.map(q => ({
    ...q,
    quizId: quizIdMap[q.quizId] // Map placeholder ID to actual ID
  }));
  const insertedQuestions = await db.insert(questions).values(questionInsertData).returning({ id: questions.id });
  console.log(`Inserted ${insertedQuestions.length} questions.`);

  console.log('Database seeded successfully with course content!');
}


// Example of how to run:
// Create a script (e.g., `seed-runner.ts`) that imports and calls `seedDatabase()`.
// import { seedDatabase } from './seed';
// seedDatabase().then(() => console.log('Seeding complete.')).catch(console.error).finally(() => process.exit(0));
// Run it using: `npx tsx -r dotenv/config path/to/seed-runner.ts`
// Ensure your database connection (db instance) is correctly configured in './storage'.

// Add a check to run seedDatabase if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  console.log('Running seed script directly...');
  seedDatabase()
    .then(() => {
      console.log('Seeding completed successfully.');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seeding failed:', error);
      process.exit(1);
    });
}
