name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Trigger on push to main branch; adjust as needed
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for AWS authentication
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push Docker image to ECR
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 156046566171.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: gohamma/landing
          IMAGE_TAG: ${{ github.sha }} # Use commit SHA as tag; adjust as needed
        run: |
          # Build the Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # Tag the image with 'latest' (optional)
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Push the image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest